grant create view to gjzspt;

SELECT * FROM DBA_TAB_PRIVS where GRANTEE IN ('GJZSPT','RESOURCE');

SELECT * FROM DBA_SYS_PRIVS WHERE grantee in ('RESOURCE','GJZSPT');

SELECT * FROM ROLE_TAB_PRIVS where ROLE IN ('RESOURCE');

SELECT * from ROLE_SYS_PRIVS where ROLE IN ('CONNECT','RESOURCE');

SELECT EXTENDED_TIMESTAMP,
  OS_USER,
  userhost,
  os_process,
  DB_USER,
  OBJECT_SCHEMA,
  OBJECT_NAME,
  RETURNCODE,
  STATEMENT_TYPE,
  SQL_TEXT,
  AUDIT_TYPE
FROM DBA_COMMON_AUDIT_TRAIL
ORDER BY EXTENDED_TIMESTAMP DESC,
  LOGOFF_TIME DESC;
  
SELECT object_name,
object_type,
created,
last_ddl_time
FROM DBA_OBJECTS
WHERE owner ='GJZSPT'
AND object_type = 'TABLE'
AND object_name LIKE 'T_DGAP%';

SELECT * FROM DBA_CONSTRAINTS 
WHERE r_owner = 'GJZSPT';