  CREATE TABLE "GJZSPT_DEMO2"."ACT_HI_ATTACHMENT" 
   (	"ID_" VARCHAR2(64) NOT NULL ENABLE,
	"REV_" NUMBER(*,0),
	"USER_ID_" VARCHAR2(255),
	"NAME_" VARCHAR2(255),
	"DESCRIPTION_" VARCHAR2(2000),
	"TYPE_" VARCHAR2(255),
	"TASK_ID_" VARCHAR2(64),
	"PROC_INST_ID_" VARCHAR2(64),
	"URL_" VARCHAR2(2000),
	"CONTENT_ID_" VARCHAR2(64),
	PRIMARY KEY ("ID_") ENABLE
   );
   
     CREATE TABLE "GJZSPT_DEMO2"."ACT_HI_COMMENT" 
   (	"ID_" VARCHAR2(64) NOT NULL ENABLE,
	"TYPE_" VARCHAR2(255),
	"TIME_" TIMESTAMP(6) NOT NULL ENABLE,
	"USER_ID_" VARCHAR2(255),
	"TASK_ID_" VARCHAR2(64),
	"PROC_INST_ID_" VARCHAR2(64),
	"ACTION_" VARCHAR2(255),
	"MESSAGE_" VARCHAR2(2000),
	"FULL_MSG_" BLOB,
	PRIMARY KEY ("ID_") ENABLE
   );
   
     CREATE TABLE "GJZSPT_DEMO2"."ACT_ID_INFO" 
   (	"ID_" VARCHAR2(64),
	"REV_" NUMBER(*,0),
	"USER_ID_" VARCHAR2(64),
	"TYPE_" VARCHAR2(64),
	"KEY_" VARCHAR2(255),
	"VALUE_" VARCHAR2(255),
	"PASSWORD_" BLOB,
	"PARENT_ID_" VARCHAR2(255),
	PRIMARY KEY ("ID_") ENABLE
   );
   
     CREATE TABLE "GJZSPT_DEMO2"."ACT_RU_EVENT_SUBSCR" 
   (	"ID_" VARCHAR2(64) NOT NULL ENABLE,
	"REV_" NUMBER(*,0),
	"EVENT_TYPE_" VARCHAR2(255) NOT NULL ENABLE,
	"EVENT_NAME_" VARCHAR2(255),
	"EXECUTION_ID_" VARCHAR2(64),
	"PROC_INST_ID_" VARCHAR2(64),
	"ACTIVITY_ID_" VARCHAR2(64),
	"CONFIGURATION_" VARCHAR2(255),
	"CREATED_" TIMESTAMP(6) NOT NULL ENABLE,
	PRIMARY KEY ("ID_") ENABLE,
	CONSTRAINT "ACT_FK_EVENT_EXEC" FOREIGN KEY ("EXECUTION_ID_")
	 REFERENCES "GJZSPT_DEMO2"."ACT_RU_EXECUTION" ("ID_") ENABLE
   );
   
     CREATE TABLE "GJZSPT_DEMO2"."ACT_RU_JOB" 
   (	"ID_" VARCHAR2(64) NOT NULL ENABLE,
	"REV_" NUMBER(*,0),
	"TYPE_" VARCHAR2(255) NOT NULL ENABLE,
	"LOCK_EXP_TIME_" TIMESTAMP(6),
	"LOCK_OWNER_" VARCHAR2(255),
	"EXCLUSIVE_" NUMBER(1,0),
	"EXECUTION_ID_" VARCHAR2(64),
	"PROCESS_INSTANCE_ID_" VARCHAR2(64),
	"PROC_DEF_ID_" VARCHAR2(64),
	"RETRIES_" NUMBER(*,0),
	"EXCEPTION_STACK_ID_" VARCHAR2(64),
	"EXCEPTION_MSG_" VARCHAR2(2000),
	"DUEDATE_" TIMESTAMP(6),
	"REPEAT_" VARCHAR2(255),
	"HANDLER_TYPE_" VARCHAR2(255),
	"HANDLER_CFG_" VARCHAR2(2000),
	CHECK (EXCLUSIVE_ IN (1,0)) ENABLE,
	CHECK (EXCLUSIVE_ IN (1,0)) ENABLE,
	PRIMARY KEY ("ID_") ENABLE,
	CONSTRAINT "ACT_FK_JOB_EXCEPTION" FOREIGN KEY ("EXCEPTION_STACK_ID_")
	 REFERENCES "GJZSPT_DEMO2"."ACT_GE_BYTEARRAY" ("ID_") ENABLE
   );
   
   ALTER TABLE "GJZSPT_DEMO2"."ADS_CHECK_PACKAGE" ADD ("CHECK_ITEM_IDS" VARCHAR2(2048));

  CREATE TABLE "GJZSPT_DEMO2"."ADS_CHECK_PROJECT" 
   (	"ID" VARCHAR2(64) NOT NULL ENABLE,
	"CHECK_PROJECT" VARCHAR2(32) NOT NULL ENABLE,
	"CHECK_NUM" VARCHAR2(32) NOT NULL ENABLE,
	"JUDGE_NUM" VARCHAR2(32) NOT NULL ENABLE,
	"RESULT" VARCHAR2(32) NOT NULL ENABLE,
	"CHECK_INFO_ID" VARCHAR2(64) NOT NULL ENABLE,
	"CREATE_BY" VARCHAR2(64) NOT NULL ENABLE,
	"CREATE_TIME" TIMESTAMP(6) NOT NULL ENABLE,
	"UPDATE_BY" VARCHAR2(64),
	"UPDATE_TIME" TIMESTAMP(6),
	"DEL_FLAG" VARCHAR2(1) DEFAULT 'N',
	"RESERVED_FIELD1" VARCHAR2(200),
	"RESERVED_FIELD2" VARCHAR2(200),
	PRIMARY KEY ("ID") ENABLE,
	CONSTRAINT "CHECK_INFO_ID_CONS" FOREIGN KEY ("CHECK_INFO_ID")
	 REFERENCES "GJZSPT_DEMO2"."ADS_CHECK_INFO" ("ID") ENABLE
   );
  COMMENT ON TABLE "GJZSPT_DEMO2"."ADS_CHECK_PROJECT" IS '检测项目';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."ADS_CHECK_PROJECT"."CHECK_INFO_ID" IS '检测信息Key';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."ADS_CHECK_PROJECT"."CHECK_NUM" IS '检出值';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."ADS_CHECK_PROJECT"."CHECK_PROJECT" IS '检测项目名称';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."ADS_CHECK_PROJECT"."ID" IS '主键id';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."ADS_CHECK_PROJECT"."JUDGE_NUM" IS '判定值';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."ADS_CHECK_PROJECT"."RESULT" IS '抽检结果';
  
  ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" MODIFY ("TESTED_DEPARMENT" VARCHAR2(512));
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("ID" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("ORGAN_TASK_ID" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_BAR_CODE" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_NAME" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_CODE" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("PRODUCE_DATE" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_PLACE" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("TESTED_DEPARMENT" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("TESTED_ADDRESS" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("TESTED_PERSON" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("PRODUCTION_DEPARMENT" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("PRODUCTION_ADDRESS" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_ID" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_DEPARMENT" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_LINKMAN" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_PERSON" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_DATE" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("CREATE_BY" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("CREATE_TIME" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("PRODUCT_TRACEABILITY_CODE" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("ID" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("ORGAN_TASK_ID" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_BAR_CODE" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_NAME" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_CODE" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("PRODUCE_DATE" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_PLACE" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("TESTED_DEPARMENT" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("TESTED_ADDRESS" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("TESTED_PERSON" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("PRODUCTION_DEPARMENT" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("PRODUCTION_ADDRESS" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_ID" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_DEPARMENT" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_LINKMAN" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_PERSON" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("SAMPLE_DATE" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("CREATE_BY" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("CREATE_TIME" IS NOT NULL) ENABLE;
ALTER TABLE "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE" ADD  CHECK ("PRODUCT_TRACEABILITY_CODE" IS NOT NULL) ENABLE;
COMMENT ON COLUMN "GJZSPT_DEMO2"."ADS_MONITOR_SAMPLE"."PRODUCTIONS_TATUS" IS '样品来源';


  CREATE TABLE "GJZSPT_DEMO2"."ALEMBIC_VERSION" 
   (	"VERSION_NUM" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	CONSTRAINT "ALEMBIC_VERSION_PKC" PRIMARY KEY ("VERSION_NUM") ENABLE
   );
   
   COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_DAILY_ENFORCE_LAW"."PRINCIPAL" IS '负责人';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_DAILY_ENFORCE_LAW"."PRINCIPAL_SIGNATURES" IS '负责人签字照片urls';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_DAILY_ENFORCE_LAW"."PRINCIPAL_SIGNATURE_NAMES" IS '负责人签字照片名称';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_DAILY_ENFORCE_LAW"."SCENE_PICTURES" IS '现场照片urls';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_DAILY_ENFORCE_LAW"."SCENE_PICTURE_NAMES" IS '现场照片名称';


COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_ENTRUST_DETECTION"."ATTACHMENTS" IS '附件url';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_ENTRUST_DETECTION"."ATTACHMENT_NAMES" IS '附件名';


  CREATE TABLE "GJZSPT_DEMO2"."ALES_ENTRUST_SAMPLE" 
   (	"ID" CHAR(64) NOT NULL ENABLE,
	"PRODUCT_CODE" VARCHAR2(200),
	"SAMPLE_CODE" VARCHAR2(200),
	"ENTRUST_DETECTION_ID" CHAR(64),
	"ENTERPRISE_ID" CHAR(64),
	"SAMPLE_ADDRESS" VARCHAR2(200),
	"SAMPLE_INFORMATION" VARCHAR2(1000),
	"SAMPLE_UNIT_ID" CHAR(64),
	"REMARK" VARCHAR2(200),
	"CREATE_BY" CHAR(64),
	"CREATE_TIME" DATE,
	"ENABLE" CHAR(1),
	"DEL_FLAG" CHAR(1),
	CONSTRAINT "PK_ALES_ENTRUST_SAMPLE" PRIMARY KEY ("ID") ENABLE
   );
   
   ALTER TABLE "GJZSPT_DEMO2"."ALES_PRODUCE_ADMIN_PUNISH" ADD ("PENALTY_SOURCE" VARCHAR2(200));
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_PRODUCE_ADMIN_PUNISH"."PENALTY_SOURCE" IS '行政处罚来源';


ALTER TABLE "GJZSPT_DEMO2"."ALES_TASK_SAMPLE" MODIFY ("PRODUCT_TRACEABILITY_CODE" VARCHAR2(100));
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_TASK_SAMPLE"."ATTACHMENTS" IS '附件文件urls';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_TASK_SAMPLE"."ATTACHMENT_NAMES" IS '附件文件名称';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_TASK_SAMPLE"."NOTE" IS '备注';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_TASK_SAMPLE"."SAMPLE_AMOUNT" IS '抽样数量';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_TASK_SAMPLE"."SAMPLE_BASE_UNIT_TYPE" IS '抽样基数单位';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_TASK_SAMPLE"."SAMPLE_SOURCE" IS '样品来源';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ALES_TASK_SAMPLE"."SAMPLE_UNIT_TYPE" IS '抽样单位';


ALTER TABLE "GJZSPT_DEMO2"."ASMS_BASE_INSPECTION" MODIFY ("HEAD_SIGN" VARCHAR2(200));


ALTER TABLE "GJZSPT_DEMO2"."ASMS_CHECK_TASK" MODIFY ("TASK_NAME" VARCHAR2(200));
COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_CHECK_TASK"."ATTACHMENT_ADDRESS" IS '附件';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_CHECK_TASK"."ATTACHMENT_NAME" IS '附件名称';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_CHECK_TASK"."FILE_NUMBER" IS '文件号';


ALTER TABLE "GJZSPT_DEMO2"."ASMS_INSPECTION_TASK" ADD ("DETAIL_CONTENT" VARCHAR2(1024));
COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_INSPECTION_TASK"."ATTACHMENT_ADDRESS" IS '附件地址';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_INSPECTION_TASK"."ATTACHMENT_NAME" IS '附件名称';


COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_MONITOR_OBJECT"."IS_SAMPLE" IS '是否已提交抽样单信息 0 未提交 1 已提交 2 部分提交';


COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_SUBJ_ENT_TEMP"."ATTACHMENT_ADDRESS" IS '附件地址';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_SUBJ_ENT_TEMP"."ATTACHMENT_NAME" IS '附件名称';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_SUBJ_ENT_TEMP"."BUSINESS_LICENCEIMG" IS '企业证件照';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_SUBJ_ENT_TEMP"."HAND_IDCARDIMG" IS '手持身份证照';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_SUBJ_ENT_TEMP"."NEGATIVE_IDCARDIMG" IS '身份证反面照';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_SUBJ_ENT_TEMP"."ORGANIZATION_CERTIFICATEIMG" IS '组织机构代码照';
COMMENT ON COLUMN "GJZSPT_DEMO2"."ASMS_SUBJ_ENT_TEMP"."POSITIVE_IDCARDEIMG" IS '身份证正面照';


ALTER TABLE "GJZSPT_DEMO2"."ASMS_SUBJ_SV_CHANGE" ADD ("WORKITEMID" VARCHAR2(100));


  CREATE TABLE "GJZSPT_DEMO2"."DBCOPYTEST" 
   (	"REMARKS" CHAR(10)
   );
   
     CREATE TABLE "GJZSPT_DEMO2"."MODEL_RULE_DRUG" 
   (	"ID" VARCHAR2(64) NOT NULL ENABLE,
	"DRUGNAME" VARCHAR2(200) NOT NULL ENABLE,
	"DRUGTYPE" VARCHAR2(64) NOT NULL ENABLE,
	"DRUGNUM" NUMBER DEFAULT 0,
	"DRUGAMOUNT" NUMBER DEFAULT 0,
	"STORAGEDATE" TIMESTAMP(6)
   );
   
  CREATE TABLE "GJZSPT_DEMO2"."QRTZ_CRON_TRIGGERS" 
   (	"SCHED_NAME" NVARCHAR2(120) NOT NULL ENABLE,
	"TRIGGER_NAME" NVARCHAR2(200) NOT NULL ENABLE,
	"TRIGGER_GROUP" NVARCHAR2(200) NOT NULL ENABLE,
	"CRON_EXPRESSION" NVARCHAR2(200) NOT NULL ENABLE,
	"TIME_ZONE_ID" NVARCHAR2(80),
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_GROUP IS NOT NULL) ENABLE,
	CHECK (CRON_EXPRESSION IS NOT NULL) ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_GROUP IS NOT NULL) ENABLE,
	CHECK (CRON_EXPRESSION IS NOT NULL) ENABLE
   );
   
  CREATE TABLE "GJZSPT_DEMO2"."QRTZ_FIRED_TRIGGERS" 
   (	"SCHED_NAME" NVARCHAR2(120) NOT NULL ENABLE,
	"ENTRY_ID" NVARCHAR2(95) NOT NULL ENABLE,
	"TRIGGER_NAME" NVARCHAR2(200) NOT NULL ENABLE,
	"TRIGGER_GROUP" NVARCHAR2(200) NOT NULL ENABLE,
	"INSTANCE_NAME" NVARCHAR2(200) NOT NULL ENABLE,
	"FIRED_TIME" NUMBER(20,0) NOT NULL ENABLE,
	"SCHED_TIME" NUMBER(20,0) NOT NULL ENABLE,
	"PRIORITY" NUMBER(11,0) NOT NULL ENABLE,
	"STATE" NVARCHAR2(16) NOT NULL ENABLE,
	"JOB_NAME" NVARCHAR2(200),
	"JOB_GROUP" NVARCHAR2(200),
	"IS_NONCONCURRENT" NVARCHAR2(1),
	"REQUESTS_RECOVERY" NVARCHAR2(1),
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (ENTRY_ID IS NOT NULL) ENABLE,
	CHECK (TRIGGER_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_GROUP IS NOT NULL) ENABLE,
	CHECK (INSTANCE_NAME IS NOT NULL) ENABLE,
	CHECK (FIRED_TIME IS NOT NULL) ENABLE,
	CHECK (SCHED_TIME IS NOT NULL) ENABLE,
	CHECK (PRIORITY IS NOT NULL) ENABLE,
	CHECK (STATE IS NOT NULL) ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (ENTRY_ID IS NOT NULL) ENABLE,
	CHECK (TRIGGER_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_GROUP IS NOT NULL) ENABLE,
	CHECK (INSTANCE_NAME IS NOT NULL) ENABLE,
	CHECK (FIRED_TIME IS NOT NULL) ENABLE,
	CHECK (SCHED_TIME IS NOT NULL) ENABLE,
	CHECK (PRIORITY IS NOT NULL) ENABLE,
	CHECK (STATE IS NOT NULL) ENABLE
   );
   
  CREATE TABLE "GJZSPT_DEMO2"."QRTZ_JOB_DETAILS" 
   (	"SCHED_NAME" NVARCHAR2(120) NOT NULL ENABLE,
	"JOB_NAME" NVARCHAR2(200) NOT NULL ENABLE,
	"JOB_GROUP" NVARCHAR2(200) NOT NULL ENABLE,
	"DESCRIPTION" NVARCHAR2(250),
	"JOB_CLASS_NAME" NVARCHAR2(250) NOT NULL ENABLE,
	"IS_DURABLE" NVARCHAR2(1) NOT NULL ENABLE,
	"IS_NONCONCURRENT" NVARCHAR2(1) NOT NULL ENABLE,
	"IS_UPDATE_DATA" NVARCHAR2(1) NOT NULL ENABLE,
	"REQUESTS_RECOVERY" NVARCHAR2(1) NOT NULL ENABLE,
	"JOB_DATA" BLOB,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (JOB_NAME IS NOT NULL) ENABLE,
	CHECK (JOB_GROUP IS NOT NULL) ENABLE,
	CHECK (JOB_CLASS_NAME IS NOT NULL) ENABLE,
	CHECK (IS_DURABLE IS NOT NULL) ENABLE,
	CHECK (IS_NONCONCURRENT IS NOT NULL) ENABLE,
	CHECK (IS_UPDATE_DATA IS NOT NULL) ENABLE,
	CHECK (REQUESTS_RECOVERY IS NOT NULL) ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (JOB_NAME IS NOT NULL) ENABLE,
	CHECK (JOB_GROUP IS NOT NULL) ENABLE,
	CHECK (JOB_CLASS_NAME IS NOT NULL) ENABLE,
	CHECK (IS_DURABLE IS NOT NULL) ENABLE,
	CHECK (IS_NONCONCURRENT IS NOT NULL) ENABLE,
	CHECK (IS_UPDATE_DATA IS NOT NULL) ENABLE,
	CHECK (REQUESTS_RECOVERY IS NOT NULL) ENABLE
   );
   
  CREATE TABLE "GJZSPT_DEMO2"."QRTZ_LOCKS" 
   (	"SCHED_NAME" NVARCHAR2(120) NOT NULL ENABLE,
	"LOCK_NAME" NVARCHAR2(40) NOT NULL ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (LOCK_NAME IS NOT NULL) ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (LOCK_NAME IS NOT NULL) ENABLE
   );
   
  CREATE TABLE "GJZSPT_DEMO2"."QRTZ_PAUSED_TRIGGER_GRPS" 
   (	"SCHED_NAME" NVARCHAR2(120) NOT NULL ENABLE,
	"TRIGGER_GROUP" NVARCHAR2(200) NOT NULL ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_GROUP IS NOT NULL) ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_GROUP IS NOT NULL) ENABLE
   );
   
  CREATE TABLE "GJZSPT_DEMO2"."QRTZ_SCHEDULER_STATE" 
   (	"SCHED_NAME" NVARCHAR2(120) NOT NULL ENABLE,
	"INSTANCE_NAME" NVARCHAR2(200) NOT NULL ENABLE,
	"LAST_CHECKIN_TIME" NUMBER(20,0) NOT NULL ENABLE,
	"CHECKIN_INTERVAL" NUMBER(20,0) NOT NULL ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (INSTANCE_NAME IS NOT NULL) ENABLE,
	CHECK (LAST_CHECKIN_TIME IS NOT NULL) ENABLE,
	CHECK (CHECKIN_INTERVAL IS NOT NULL) ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (INSTANCE_NAME IS NOT NULL) ENABLE,
	CHECK (LAST_CHECKIN_TIME IS NOT NULL) ENABLE,
	CHECK (CHECKIN_INTERVAL IS NOT NULL) ENABLE
   );
   
  CREATE TABLE "GJZSPT_DEMO2"."QRTZ_SIMPLE_TRIGGERS" 
   (	"SCHED_NAME" NVARCHAR2(120) NOT NULL ENABLE,
	"TRIGGER_NAME" NVARCHAR2(200) NOT NULL ENABLE,
	"TRIGGER_GROUP" NVARCHAR2(200) NOT NULL ENABLE,
	"REPEAT_COUNT" NUMBER(20,0) NOT NULL ENABLE,
	"REPEAT_INTERVAL" NUMBER(20,0) NOT NULL ENABLE,
	"TIMES_TRIGGERED" NUMBER(20,0) NOT NULL ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_GROUP IS NOT NULL) ENABLE,
	CHECK (REPEAT_COUNT IS NOT NULL) ENABLE,
	CHECK (REPEAT_INTERVAL IS NOT NULL) ENABLE,
	CHECK (TIMES_TRIGGERED IS NOT NULL) ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_GROUP IS NOT NULL) ENABLE,
	CHECK (REPEAT_COUNT IS NOT NULL) ENABLE,
	CHECK (REPEAT_INTERVAL IS NOT NULL) ENABLE,
	CHECK (TIMES_TRIGGERED IS NOT NULL) ENABLE
   );
   
  CREATE TABLE "GJZSPT_DEMO2"."QRTZ_SIMPROP_TRIGGERS" 
   (	"SCHED_NAME" NVARCHAR2(120) NOT NULL ENABLE,
	"TRIGGER_NAME" NVARCHAR2(200) NOT NULL ENABLE,
	"TRIGGER_GROUP" NVARCHAR2(200) NOT NULL ENABLE,
	"STR_PROP_1" NVARCHAR2(512),
	"STR_PROP_2" NVARCHAR2(512),
	"STR_PROP_3" NVARCHAR2(512),
	"INT_PROP_1" NUMBER(11,0),
	"INT_PROP_2" NUMBER(11,0),
	"LONG_PROP_1" NUMBER(20,0),
	"LONG_PROP_2" NUMBER(20,0),
	"DEC_PROP_1" NUMBER,
	"DEC_PROP_2" NUMBER,
	"BOOL_PROP_1" NVARCHAR2(1),
	"BOOL_PROP_2" NVARCHAR2(1),
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_GROUP IS NOT NULL) ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_GROUP IS NOT NULL) ENABLE
   );
   
  CREATE TABLE "GJZSPT_DEMO2"."QRTZ_TRIGGERS" 
   (	"SCHED_NAME" NVARCHAR2(120) NOT NULL ENABLE,
	"TRIGGER_NAME" NVARCHAR2(200) NOT NULL ENABLE,
	"TRIGGER_GROUP" NVARCHAR2(200) NOT NULL ENABLE,
	"JOB_NAME" NVARCHAR2(200) NOT NULL ENABLE,
	"JOB_GROUP" NVARCHAR2(200) NOT NULL ENABLE,
	"DESCRIPTION" NVARCHAR2(250),
	"NEXT_FIRE_TIME" NUMBER(20,0),
	"PREV_FIRE_TIME" NUMBER(20,0),
	"PRIORITY" NUMBER(11,0),
	"TRIGGER_STATE" NVARCHAR2(16) NOT NULL ENABLE,
	"TRIGGER_TYPE" NVARCHAR2(8) NOT NULL ENABLE,
	"START_TIME" NUMBER(20,0) NOT NULL ENABLE,
	"END_TIME" NUMBER(20,0),
	"CALENDAR_NAME" NVARCHAR2(200),
	"MISFIRE_INSTR" NUMBER(6,0),
	"JOB_DATA" BLOB,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_GROUP IS NOT NULL) ENABLE,
	CHECK (JOB_NAME IS NOT NULL) ENABLE,
	CHECK (JOB_GROUP IS NOT NULL) ENABLE,
	CHECK (TRIGGER_STATE IS NOT NULL) ENABLE,
	CHECK (TRIGGER_TYPE IS NOT NULL) ENABLE,
	CHECK (START_TIME IS NOT NULL) ENABLE,
	CHECK (SCHED_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_NAME IS NOT NULL) ENABLE,
	CHECK (TRIGGER_GROUP IS NOT NULL) ENABLE,
	CHECK (JOB_NAME IS NOT NULL) ENABLE,
	CHECK (JOB_GROUP IS NOT NULL) ENABLE,
	CHECK (TRIGGER_STATE IS NOT NULL) ENABLE,
	CHECK (TRIGGER_TYPE IS NOT NULL) ENABLE,
	CHECK (START_TIME IS NOT NULL) ENABLE
   );
   
ALTER TABLE "GJZSPT_DEMO2"."SYS_CODE_CONVERT" ADD CONSTRAINT "SYS_CODE_LONG_UNIQUE" UNIQUE ("CODE_LONG") DISABLE;


ALTER TABLE "GJZSPT_DEMO2"."SYS_DICT_DATA" ADD CONSTRAINT "SYS_DICT_DATA_ID_PK" PRIMARY KEY ("ID") ENABLE;


ALTER TABLE "GJZSPT_DEMO2"."SYS_DICT_TYPE" ADD CONSTRAINT "PK_SYS_DICT_TYPE" PRIMARY KEY ("ID") ENABLE;


  CREATE TABLE "GJZSPT_DEMO2"."SYS_DOCUMENT" 
   (	"ID" VARCHAR2(64) NOT NULL ENABLE,
	"TITLE" VARCHAR2(500 CHAR) DEFAULT '' NOT NULL ENABLE,
	"CONTENT" CLOB DEFAULT '' NOT NULL ENABLE,
	"TYPE" VARCHAR2(100 CHAR),
	"APPLY_TO" VARCHAR2(100 CHAR),
	"ENABLE_FLAG" VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATE_BY" VARCHAR2(64 CHAR),
	"CREATE_TIME" DATE DEFAULT sysdate,
	"UPDATE_BY" VARCHAR2(64 CHAR),
	"UPDATE_TIME" DATE,
	"DEL_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
	PRIMARY KEY ("ID") ENABLE
   );
  COMMENT ON TABLE "GJZSPT_DEMO2"."SYS_DOCUMENT" IS '文档表';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_DOCUMENT"."APPLY_TO" IS '适用系统';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_DOCUMENT"."CONTENT" IS '内容（存放前端富文本框生成的html）';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_DOCUMENT"."CREATE_BY" IS '创建人';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_DOCUMENT"."CREATE_TIME" IS '创建时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_DOCUMENT"."DEL_FLAG" IS '删除标记（Y：已删除，N：未删除）';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_DOCUMENT"."ENABLE_FLAG" IS '启用标记（Y：启用，N：禁用）';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_DOCUMENT"."ID" IS 'ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_DOCUMENT"."TITLE" IS '标题';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_DOCUMENT"."TYPE" IS '类别';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_DOCUMENT"."UPDATE_BY" IS '更新人';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_DOCUMENT"."UPDATE_TIME" IS '更新时间';
  
  CREATE TABLE "GJZSPT_DEMO2"."SYS_FLOW_ACTER" 
   (	"ID" VARCHAR2(64) NOT NULL ENABLE,
	"FLOW_ID" VARCHAR2(64),
	"FLOW_NODE_ID" VARCHAR2(64),
	"ROLE_ID" VARCHAR2(64),
	"CREATE_BY" VARCHAR2(64),
	"CREATE_TIME" TIMESTAMP(6),
	"UPDATE_BY" VARCHAR2(64),
	"UPDATE_TIME" TIMESTAMP(6),
	"DEL_FLAG" VARCHAR2(1) DEFAULT 'N',
	"RESERVED_FIELD1" VARCHAR2(200),
	"RESERVED_FIELD2" VARCHAR2(200),
	CONSTRAINT "PK_SYS_FLOW_ACTER" PRIMARY KEY ("ID") ENABLE
   );
  COMMENT ON TABLE "GJZSPT_DEMO2"."SYS_FLOW_ACTER" IS '流程参与者表';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_ACTER"."CREATE_BY" IS '创建人ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_ACTER"."CREATE_TIME" IS '创建时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_ACTER"."DEL_FLAG" IS '删除标识';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_ACTER"."FLOW_ID" IS '流程ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_ACTER"."FLOW_NODE_ID" IS '流程节点ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_ACTER"."ID" IS 'ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_ACTER"."RESERVED_FIELD1" IS '预留字段1';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_ACTER"."RESERVED_FIELD2" IS '预留字段2';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_ACTER"."ROLE_ID" IS '角色ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_ACTER"."UPDATE_BY" IS '修改人ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_ACTER"."UPDATE_TIME" IS '修改时间';
  
  CREATE TABLE "GJZSPT_DEMO2"."SYS_FLOW_NODE" 
   (	"ID" VARCHAR2(64) NOT NULL ENABLE,
	"FLOW_ID" VARCHAR2(64),
	"NODE_NAME" VARCHAR2(64),
	"NODE_CODE" VARCHAR2(64),
	"SORTNO" VARCHAR2(64),
	"STATUS" VARCHAR2(64),
	"REMARK" CHAR(10),
	"CREATE_BY" VARCHAR2(64),
	"CREATE_TIME" TIMESTAMP(6),
	"UPDATE_BY" VARCHAR2(64),
	"UPDATE_TIME" TIMESTAMP(6),
	"DEL_FLAG" VARCHAR2(1) DEFAULT 'N',
	"RESERVED_FIELD1" VARCHAR2(200),
	"RESERVED_FIELD2" VARCHAR2(200),
	CONSTRAINT "PK_SYS_FLOW_NODE" PRIMARY KEY ("ID") ENABLE
   );
  COMMENT ON TABLE "GJZSPT_DEMO2"."SYS_FLOW_NODE" IS '流程节点表';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."CREATE_BY" IS '创建人ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."CREATE_TIME" IS '创建时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."DEL_FLAG" IS '删除标识';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."FLOW_ID" IS '流程ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."ID" IS 'ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."NODE_CODE" IS '节点编码';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."NODE_NAME" IS '节点名';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."REMARK" IS '备注';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."RESERVED_FIELD1" IS '预留字段1';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."RESERVED_FIELD2" IS '预留字段2';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."SORTNO" IS '序号';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."STATUS" IS '状态';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."UPDATE_BY" IS '修改人ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_FLOW_NODE"."UPDATE_TIME" IS '修改时间';
  
ALTER TABLE "GJZSPT_DEMO2"."SYS_ORGANIZATION" MODIFY ("ORG_NAME" VARCHAR2(150));

ALTER TABLE "GJZSPT_DEMO2"."SYS_PESTICIDE_RESIDUES" DROP CONSTRAINT SYS_C0063264;


  CREATE TABLE "GJZSPT_DEMO2"."SYS_POST" 
   (	"ID" VARCHAR2(64) NOT NULL ENABLE,
	"DEPT_ID" VARCHAR2(64),
	"POST_TYPE" VARCHAR2(64),
	"POST_LEVEL" VARCHAR2(64),
	"POST_NAME" VARCHAR2(50),
	"STATUS" VARCHAR2(64),
	"CREATE_BY" VARCHAR2(64),
	"CREATE_TIME" TIMESTAMP(6),
	"UPDATE_BY" VARCHAR2(64),
	"UPDATE_TIME" TIMESTAMP(6),
	"DEL_FLAG" VARCHAR2(1) DEFAULT 'N',
	"RESERVED_FIELD1" VARCHAR2(200),
	"RESERVED_FIELD2" VARCHAR2(200),
	CONSTRAINT "PK_SYS_POST" PRIMARY KEY ("ID") ENABLE
   );
  COMMENT ON TABLE "GJZSPT_DEMO2"."SYS_POST" IS '职务表';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."CREATE_BY" IS '创建人ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."CREATE_TIME" IS '创建时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."DEL_FLAG" IS '删除标识';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."DEPT_ID" IS '所属部门ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."ID" IS 'ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."POST_LEVEL" IS '职务级别';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."POST_NAME" IS '职务名称';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."POST_TYPE" IS '职务类别';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."RESERVED_FIELD1" IS '预留字段1';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."RESERVED_FIELD2" IS '预留字段2';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."STATUS" IS '状态ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."UPDATE_BY" IS '修改人ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_POST"."UPDATE_TIME" IS '修改时间';
  
COMMENT ON TABLE "GJZSPT_DEMO2"."SYS_TEMPLATE" IS '模板表';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."CREATE_BY" IS '创建人ID';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."DEL_FLAG" IS '删除标识';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."ID" IS 'ID';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."REMARK" IS '备注';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."RESERVED_FIELD1" IS '预留字段1';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."RESERVED_FIELD2" IS '预留字段2';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."STATUS" IS '状态';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."TEMPLATE_FILENAME" IS '模板文件名';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."TEMPLATE_NAME" IS '模板名称';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."TEMPLATE_TYPE" IS '模板类型';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."UPDATE_BY" IS '修改人ID';
COMMENT ON COLUMN "GJZSPT_DEMO2"."SYS_TEMPLATE"."UPDATE_TIME" IS '修改时间';


  CREATE TABLE "GJZSPT_DEMO2"."TASK_FIRE_LOG" 
   (	"ID_" NVARCHAR2(64) NOT NULL ENABLE,
	"GROUP_NAME" NVARCHAR2(50) NOT NULL ENABLE,
	"TASK_NAME" NVARCHAR2(50) NOT NULL ENABLE,
	"START_TIME" DATE NOT NULL ENABLE,
	"END_TIME" DATE,
	"STATUS" NVARCHAR2(1) NOT NULL ENABLE,
	"SERVER_HOST" NVARCHAR2(50),
	"SERVER_DUID" NVARCHAR2(50),
	"FIRE_INFO" NCLOB,
	CHECK (id_ IS NOT NULL) ENABLE,
	CHECK (group_name IS NOT NULL) ENABLE,
	CHECK (task_name IS NOT NULL) ENABLE,
	CHECK (start_time IS NOT NULL) ENABLE,
	CHECK (status IS NOT NULL) ENABLE,
	CHECK (id_ IS NOT NULL) ENABLE,
	CHECK (group_name IS NOT NULL) ENABLE,
	CHECK (task_name IS NOT NULL) ENABLE,
	CHECK (start_time IS NOT NULL) ENABLE,
	CHECK (status IS NOT NULL) ENABLE
   );
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TASK_FIRE_LOG"."SERVER_DUID" IS '服务器网卡序列号';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TASK_FIRE_LOG"."SERVER_HOST" IS '服务器名';
  
  CREATE TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2" 
   (	"ID" VARCHAR2(64) NOT NULL ENABLE,
	"TITLE" VARCHAR2(200),
	"MESSAGE" VARCHAR2(2000),
	"FROM_ID" VARCHAR2(64),
	"FROM_NAME" VARCHAR2(64),
	"TO_ID" VARCHAR2(64),
	"TO_NAME" VARCHAR2(64),
	"ISREAD" VARCHAR2(1),
	"DEL_FLAG" VARCHAR2(1),
	"CREATE_TIME" DATE,
	"CREATE_BY" VARCHAR2(64),
	"UPDATE_TIME" DATE,
	"UPDATE_BY" VARCHAR2(64)
   );
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."CREATE_BY" IS '创建人';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."CREATE_TIME" IS '创建时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."DEL_FLAG" IS '删除标识';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."FROM_ID" IS '来源id';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."FROM_NAME" IS '来源名称';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."ID" IS 'id';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."ISREAD" IS '是否阅读';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."MESSAGE" IS '消息';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."TITLE" IS '标题';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."TO_ID" IS '去向id';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."TO_NAME" IS '去向名称';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."UPDATE_BY" IS '更新人';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_MESSAGE_V2"."UPDATE_TIME" IS '更新时间';
  
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" ADD ("FROM_ID" VARCHAR2(64));
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" ADD ("FROM_NAME" VARCHAR2(64));
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" ADD ("ISREAD" VARCHAR2(2));
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" ADD ("TO_ID" VARCHAR2(64));
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" ADD ("TO_NAME" VARCHAR2(64));
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("BE_ENTITY_IDCODE");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("BE_USER_IDCODE");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("ENTITY_IDCODE");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD1");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD10");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD11");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD12");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD13");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD14");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD15");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD16");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD17");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD18");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD19");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD2");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD20");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD3");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD4");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD5");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD6");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD7");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD8");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("RESERVED_FIELD9");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2" DROP ("USER_IDCODE");
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2"."BE_ENTITY_IDCODE" IS '';
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2"."BE_USER_IDCODE" IS '';
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2"."ENTITY_IDCODE" IS '';
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2"."USER_IDCODE" IS '';
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2"."FROM_ID" IS '来源ID';
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2"."FROM_NAME" IS '来源名称';
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2"."ISREAD" IS '是否阅读';
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2"."TO_ID" IS '去向ID';
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_NOTIFICATION_V2"."TO_NAME" IS '去向名称';


  CREATE TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE" 
   (	"ID" VARCHAR2(64) NOT NULL ENABLE,
	"PRODUCT_ID" VARCHAR2(64),
	"PRODUCT_NAME" VARCHAR2(400),
	"PRODUCT_TYPE" VARCHAR2(255),
	"PRODUCT_INDUSTRY" VARCHAR2(255),
	"PRODUCT_SORT" VARCHAR2(255),
	"PRODUCT_AMOUNT" VARCHAR2(255),
	"FREEZE_COUNT" VARCHAR2(255),
	"STORE_COUNT" VARCHAR2(255),
	"HARVEST_UNIT" VARCHAR2(255),
	"HARVEST_TIME" DATE,
	"PRODUCT_PC" VARCHAR2(64),
	"CHECK_IMAGENAME" VARCHAR2(255),
	"CHECK_IMAGEPATH" VARCHAR2(255),
	"PRODUCT_INNER_KEY" VARCHAR2(100),
	"PRODUCT_SOURCE" VARCHAR2(255),
	"MEDI_CHECK" VARCHAR2(100),
	"MEDI_RESULT" VARCHAR2(100),
	"HARVEST_BASEID" VARCHAR2(100),
	"HARVEST_BASENAME" VARCHAR2(255),
	"STATRUS" VARCHAR2(1),
	"BILL_STRATRUS" VARCHAR2(1),
	"IP" VARCHAR2(140),
	"CREATE_BY" CHAR(32),
	"CREATE_TIME" DATE,
	"UPDATE_BY" CHAR(32),
	"UPDATE_TIME" DATE,
	"ENABLE" VARCHAR2(1),
	"RESERVED_FIELD1" VARCHAR2(200),
	"RESERVED_FIELD2" VARCHAR2(200),
	"RESERVED_FIELD3" VARCHAR2(200),
	"RESERVED_FIELD4" VARCHAR2(200),
	"RESERVED_FIELD5" VARCHAR2(200),
	"RESERVED_FIELD6" VARCHAR2(200),
	"RESERVED_FIELD7" VARCHAR2(200),
	"RESERVED_FIELD8" VARCHAR2(200),
	"RESERVED_FIELD9" VARCHAR2(200),
	"RESERVED_FIELD10" VARCHAR2(200),
	"RESERVED_FIELD11" VARCHAR2(200),
	"RESERVED_FIELD12" VARCHAR2(200),
	"RESERVED_FIELD13" VARCHAR2(200),
	"RESERVED_FIELD14" VARCHAR2(200),
	"RESERVED_FIELD15" VARCHAR2(200),
	"RESERVED_FIELD16" VARCHAR2(200),
	"RESERVED_FIELD17" VARCHAR2(200),
	"RESERVED_FIELD18" VARCHAR2(200),
	"RESERVED_FIELD19" VARCHAR2(200),
	"RESERVED_FIELD20" VARCHAR2(200),
	PRIMARY KEY ("ID") ENABLE
   );
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."BILL_STRATRUS" IS '单据状态';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."CHECK_IMAGENAME" IS '质检照片名称';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."CHECK_IMAGEPATH" IS '质检照片路径';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."FREEZE_COUNT" IS '冻结数量';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."HARVEST_BASEID" IS '收获基地id';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."HARVEST_BASENAME" IS '收获基地名称';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."HARVEST_TIME" IS '收获时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."HARVEST_UNIT" IS '收获单位(计量单位)';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."IP" IS '当前设备IP地址';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."MEDI_CHECK" IS '质检情况：送检/自检';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."MEDI_RESULT" IS '质检结论：合格/不合格';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."PRODUCT_AMOUNT" IS '收获数量';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."PRODUCT_ID" IS '产品名称';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."PRODUCT_INDUSTRY" IS '所属行业';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."PRODUCT_INNER_KEY" IS '内部追溯批次MA';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."PRODUCT_NAME" IS '产品名称';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."PRODUCT_PC" IS '产品批次';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."PRODUCT_SORT" IS '产品分类';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."PRODUCT_SOURCE" IS '产品来源';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."PRODUCT_TYPE" IS '产品分类';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."STATRUS" IS '当前状态';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_PRODUCTION_MANAGE"."STORE_COUNT" IS '库存数量';
  
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" MODIFY ("ORGANIZATION_CODE" VARCHAR2(200));
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" MODIFY ("REGISTER_TIME" NULL);
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063498;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063499;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063500;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063501;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063502;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063503;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063504;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063505;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063506;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063507;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063508;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063509;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063510;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063511;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063512;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063513;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063514;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063515;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063516;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063517;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063518;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063519;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063520;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063521;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063522;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063523;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063524;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063525;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063526;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063527;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063528;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063529;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063530;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063531;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063532;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063533;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063534;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063535;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063536;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063537;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063538;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063539;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063540;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063541;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063542;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063543;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063544;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063545;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063546;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063547;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063548;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063549;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063550;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063551;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063552;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063553;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063556;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063557;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063558;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063559;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063560;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063561;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063562;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063563;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063564;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063565;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063566;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063567;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063568;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063569;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063570;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063571;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063572;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063573;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063574;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063575;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063576;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063577;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063578;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063579;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063580;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063581;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063582;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063583;
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2" DROP CONSTRAINT SYS_C0063584;
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER_V2"."APPROVE_STATUS" IS '审批状态 0:注册待审核;1:审核通过;2:注册审核不通过;3变更待审核;4:注销待审核;5:撤销待审核;6:撤销通过;7:已注销';


  CREATE TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD" 
   (	"ID" VARCHAR2(64) NOT NULL ENABLE,
	"PRODUCT_NAME" VARCHAR2(200),
	"PRODUCT_ID" VARCHAR2(200),
	"PRODUCT_INDUSTRY" VARCHAR2(200),
	"PRODUCT_SORT" VARCHAR2(200),
	"PRODUCT_SCGL_ID" VARCHAR2(200),
	"SALE_AMOUNT" NUMBER(16,4),
	"ENTITY_IDCODE" VARCHAR2(200),
	"USER_IDCODE" VARCHAR2(300),
	"CUSTOMER_ENTITY_IDCODE" VARCHAR2(200),
	"CUSTOMER_USER_IDCODE" VARCHAR2(300),
	"IS_CIRCULATES_END" VARCHAR2(1),
	"CONFIRM_STATE" VARCHAR2(1),
	"TRACE_CODE" VARCHAR2(100),
	"TRACE_PROOF" VARCHAR2(100),
	"SALE_TIME" DATE,
	"CONFIRM_TIME" DATE,
	"PRODUCT_MODEL" VARCHAR2(100),
	"BUY_COM_USER_ID" VARCHAR2(64),
	"SALE_USER" VARCHAR2(100),
	"IP_ADDRESS" VARCHAR2(140),
	"DEL_FLAG" VARCHAR2(1),
	"CREATE_BY" VARCHAR2(64),
	"UPDATE_BY" VARCHAR2(64),
	"CREATE_TIME" DATE,
	"UPDATE_TIME" DATE,
	"PRODUCT_XSPC" VARCHAR2(200),
	"XSDJ_ID" VARCHAR2(200),
	"CUSTOMER_ID" VARCHAR2(200),
	"FROM_TRACE_CODE" VARCHAR2(100),
	"TO_TRACE_CODE" VARCHAR2(100),
	PRIMARY KEY ("ID") ENABLE
   );
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."BUY_COM_USER_ID" IS '客户ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."CONFIRM_STATE" IS '确认状态';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."CONFIRM_TIME" IS '确认时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."CREATE_BY" IS '创建人ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."CREATE_TIME" IS '创建时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."CUSTOMER_ENTITY_IDCODE" IS '客户主体身份码';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."CUSTOMER_ID" IS '客户ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."CUSTOMER_USER_IDCODE" IS '客户主体用户码';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."DEL_FLAG" IS '删除标识';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."ENTITY_IDCODE" IS '主体身份码';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."FROM_TRACE_CODE" IS '来源追溯码';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."ID" IS 'id';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."IP_ADDRESS" IS 'Ip地址';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."IS_CIRCULATES_END" IS '是否入市';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."PRODUCT_ID" IS '产品ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."PRODUCT_INDUSTRY" IS '产品所属行业';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."PRODUCT_MODEL" IS '规格型号';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."PRODUCT_NAME" IS '产品名称';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."PRODUCT_SCGL_ID" IS '产品批次';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."PRODUCT_SORT" IS '产品分类';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."PRODUCT_XSPC" IS '销售批次';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."SALE_AMOUNT" IS '销售数量';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."SALE_TIME" IS '销售时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."SALE_USER" IS '销售人';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."TO_TRACE_CODE" IS '去向追溯码';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."TRACE_CODE" IS '产品追溯码';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."TRACE_PROOF" IS '入市追溯凭证';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."UPDATE_BY" IS '修改人ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."UPDATE_TIME" IS '修改时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."USER_IDCODE" IS '主体用户码';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_SLAUGHTER_SRECORD"."XSDJ_ID" IS '销售登记ID';
  
  CREATE TABLE "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI" 
   (	"ID" VARCHAR2(64) NOT NULL ENABLE,
	"PLATFORM_NAME" VARCHAR2(500 CHAR) NOT NULL ENABLE,
	"PLATFORM_AREA_ID" VARCHAR2(64 CHAR) NOT NULL ENABLE,
	"PLATFORM_LEVEL" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"INDUSTRY" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"URL" VARCHAR2(500 CHAR) NOT NULL ENABLE,
	"NOTE" VARCHAR2(500 CHAR),
	"APPLICANT" VARCHAR2(64 CHAR) NOT NULL ENABLE,
	"APPLICATION_TIME" DATE,
	"APPLICATION_DEPARTMENT" VARCHAR2(500 CHAR),
	"AUDIT_USER_ID" VARCHAR2(64 CHAR),
	"AUDIT_TIME" DATE,
	"AUDIT_COMMENTS" VARCHAR2(500 CHAR),
	"STATUS" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"CREATE_TIME" DATE NOT NULL ENABLE,
	"CREATE_BY" VARCHAR2(64 CHAR) NOT NULL ENABLE,
	"UPDATE_TIME" DATE,
	"UPDATE_BY" VARCHAR2(64 CHAR),
	"DEL_FLAG" VARCHAR2(7) NOT NULL ENABLE,
	CONSTRAINT "PK_T_DGAP_LOCAL_PLATFORM_APPLI" PRIMARY KEY ("ID") ENABLE
   );
  COMMENT ON TABLE "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI" IS '地方平台申请审核表';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."APPLICANT" IS '申请人';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."APPLICATION_DEPARTMENT" IS '申请单位';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."APPLICATION_TIME" IS '申请时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."AUDIT_COMMENTS" IS '审核意见';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."AUDIT_TIME" IS '审核时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."AUDIT_USER_ID" IS '审核人';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."CREATE_BY" IS '创建人';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."CREATE_TIME" IS '创建时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."ID" IS 'ID';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."INDUSTRY" IS '平台行业，可选值（AGRICUTURE,HUSBANDRY,AQUACULTURE）';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."NOTE" IS '备注';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."PLATFORM_AREA_ID" IS '平台所属区域';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."PLATFORM_LEVEL" IS '平台级别，可选值（PROVINCE,CITY,COUNTY）';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."PLATFORM_NAME" IS '平台名称';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."STATUS" IS '状态，可选值（NEW,APPLICATED,APPROVED,REJECTED,STARTED,STOPPED）';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."UPDATE_BY" IS '修改人';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."UPDATE_TIME" IS '修改时间';
  COMMENT ON COLUMN "GJZSPT_DEMO2"."T_DGAP_LOCAL_PLATFORM_APPLI"."URL" IS '平台网址';
  
  CREATE TABLE "GJZSPT_DEMO2"."T_MDM_BASIC_CODES" 
   (	"ID" VARCHAR2(64) NOT NULL ENABLE,
	"NAME" VARCHAR2(64),
	"FORMAT" VARCHAR2(256),
	"STATUS" CHAR(1),
	"NORMAL" VARCHAR2(256),
	"MARK" VARCHAR2(256),
	"DESCRIPTION" VARCHAR2(256),
	"BATCH" VARCHAR2(256),
	"PRINCIPLE" VARCHAR2(256),
	"PARENT_ID" VARCHAR2(64),
	"PARENT_IDS" VARCHAR2(64),
	"CREATE_BY" VARCHAR2(64),
	"CREATEDATE" TIMESTAMP(6),
	"UPDATE_BY" VARCHAR2(64),
	"UPDATEDATE" TIMESTAMP(6),
	"DEL_FLAG" CHAR(1),
	"REMARKS" VARCHAR2(255)
   );
   
ALTER TABLE "GJZSPT_DEMO2"."T_SCLTXXCJ_BASE_V2" ADD ("DICT_NAME" VARCHAR2(10));
COMMENT ON COLUMN "GJZSPT_DEMO2"."T_SCLTXXCJ_BASE_V2"."DICT_NAME" IS '基地单位';

---------------------------------------------------------------------------------------

ALTER TABLE "GJZSPT_DEMO2"."ADS_CHECK_INFO" MODIFY ("SAMPLE_NAME" VARCHAR2(32));
ALTER TABLE "GJZSPT_DEMO2"."ADS_CHECK_INFO" MODIFY ("TESTED_DEPARMENT" VARCHAR2(200));

ALTER TABLE "GJZSPT_DEMO2"."ASMS_INSPECTION_TASK" MODIFY ("CREATE_ORG_NAME" VARCHAR2(56));

ALTER TABLE "GJZSPT_DEMO2"."SYS_TEST_ITEMS" DROP CONSTRAINT SYS_C0063281;

ALTER TABLE "GJZSPT_DEMO2"."SYS_TEST_STANDARD" DROP CONSTRAINT SYS_C0063284;

ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_CHANGERECORD_V2" DROP ("RESERVED_FIELD6");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_CHANGERECORD_V2" MODIFY ("APPROVE_OPINION" VARCHAR2(1000));
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_CHANGERECORD_V2"."INFO_UNIQUE" IS '该字段为冗余字段，只用于防止注册信息出现重复的情况。';

ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER" ADD ("INFO_UNIQUE" VARCHAR2(200));
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER" MODIFY ("ENTITY_INDUSTRY" NULL);
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER" MODIFY ("ENTITY_PROPERTY" NULL);
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER" MODIFY ("ENTITY_TYPE" NULL);
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER" MODIFY ("LATITUDE" NULL);
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER" MODIFY ("LONGITUDE" NULL);
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_REGISTER" ADD CONSTRAINT "acc" UNIQUE ("RESERVED_FIELD2") ENABLE;

ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_USER_CHANGERECORD" ADD ("INFO_UNIQUE" VARCHAR2(200));
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_USER_CHANGERECORD" DROP ("RESERVED_FIELD6");
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_USER_CHANGERECORD"."INFO_UNIQUE" IS '该字段为冗余字段，只用于防止注册信息出现重复的情况。';

ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_USER_V2" ADD ("CHECK_EDIT_PASSWORD" VARCHAR2(200));
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_USER_V2" ADD ("WHETHER_PASSWORD" VARCHAR2(200));
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_USER_V2" DROP ("RESERVED_FIELD3");
ALTER TABLE "GJZSPT_DEMO2"."TTS_SCLTXXCJ_USER_V2" DROP ("RESERVED_FIELD4");
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_USER_V2"."CHECK_EDIT_PASSWORD" IS '用户是否已经修改了初始密码。0表示未修改，1表示已修改，当该字段值为1时，WHETHER_PASSWORD字段的值也必须为1';
COMMENT ON COLUMN "GJZSPT_DEMO2"."TTS_SCLTXXCJ_USER_V2"."WHETHER_PASSWORD" IS '用户是否继续接收系统提示修改初始密码的弹窗。0表示继续弹窗提示，1表示忽略';


